---

all:
  children:
    DockerSwarm:
      hosts:
        maas-machine-1:
          ansible_host: 192.168.100.201
        maas-machine-2:
          ansible_host: 192.168.100.202
      vars:
        ansible_user: ubuntu
        ansible_connection: ssh
        ansible_port: 22
    OpenStack:
      hosts:
        maas-machine-3:
          ansible_host: 192.168.100.203
      vars:
        ansible_user: ubuntu
        ansible_connection: ssh
        ansible_port: 22
    Kubernetes:
      children:
        DockerSwarm:
    Kubernetes_control-plane:
      hosts:
        maas-machine-1:
        maas-machine-2:
